SET(CMAKE_SYSTEM_PROCESSOR "aarch64")
SET(CMAKE_SYSTEM_NAME Linux)

IF(CMAKE_HOST_LINUX)
  SET(HOST_EXECUTABLE_SUFFIX "")
ENDIF(CMAKE_HOST_LINUX)
SET(CMAKE_SYSTEM_PROCESSOR aarch64-none)

SET(AARCH64_LINUX_HOST /opt/modsar/SDK/arm64/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu/bin)
#SET(CMAKE_MAKE_PROGRAM "usr/bin/make${HOST_EXECUTABLE_SUFFIX}"    CACHE PATH "QNX Make Program")
#SET(CMAKE_SH           "usr/bin/sh${HOST_EXECUTABLE_SUFFIX}"      CACHE PATH "QNX shell Program")

SET(CMAKE_AR           "${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-ar${HOST_EXECUTABLE_SUFFIX}"      CACHE PATH "Android ar Program")
SET(CMAKE_RANLIB       "${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-ranlib${HOST_EXECUTABLE_SUFFIX}"      CACHE PATH "Android ranlib Program")
SET(CMAKE_NM           "${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-nm${HOST_EXECUTABLE_SUFFIX}"      CACHE PATH "Android nm Program")
SET(CMAKE_OBJCOPY      "${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-objcopy${HOST_EXECUTABLE_SUFFIX}" CACHE PATH "Android objcopy Program")
SET(CMAKE_OBJDUMP      "${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-objdump${HOST_EXECUTABLE_SUFFIX}" CACHE PATH "Android objdump Program")
SET(CMAKE_LINKER       "${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-ld"     CACHE PATH "Android Linker Program")
SET(CMAKE_STRIP        "${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-strip${HOST_EXECUTABLE_SUFFIX}"   CACHE PATH "Android Strip Program")

SET(CMAKE_C_COMPILER ${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-gcc${HOST_EXECUTABLE_SUFFIX})
SET(CMAKE_C_FLAGS_DEBUG "-g")
SET(CMAKE_C_FLAGS_MINSIZEREL "-Os -DNDEBUG")
SET(CMAKE_C_FLAGS_RELEASE "-O3 -DNDEBUG")
SET(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -g")

SET(CMAKE_CXX_COMPILER ${AARCH64_LINUX_HOST}/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu-c++${HOST_EXECUTABLE_SUFFIX})
SET(CMAKE_CXX_FLAGS_DEBUG "-g")
SET(CMAKE_CXX_FLAGS_MINSIZEREL "-Os -DNDEBUG")
SET(CMAKE_CXX_FLAGS_RELEASE "-O3 -DNDEBUG")
SET(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g")

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

